### ISSUE TITLE
Data set issue

### ISSUE THREAD

**Issue by krishanharwani** [sinanw/llm-security-prompt-injection#2]
Try taking  larger dataset as this dataset is too small for classifying the data

**Comment by krishanharwani** [comment]
![Screenshot 2024-04-02 131543](https://github.com/sinanw/llm-security-prompt-injection/assets/40821441/4204f299-86b0-4568-885c-cf9e66568b3b)

**Comment by sinanw** [comment]
Yes, that's correct, indeed, this dataset was the only one publically available at the time of this experiment, and it was intentionally created/collected for the purpose of LLMs prompt injection classification. Please share with us if you know a larger dataset that is publicly accessible.
